server:
  port: 18080

spring:
  application:
    name: Shop-System
  cloud:
    nacos:
      discovery:
        server-addr: 121.5.40.72:8848
  redis:
    database: 0
    host: 121.5.40.72
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
    password: 123456
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: ShopHikariPool
      primary: base
      datasource:
        base:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://121.5.40.72:3306/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      p6spy: true
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

mybatis-plus:
  type-aliases-package: com.shuaibi.shop.common.entity.table
  type-enums-package: com.shuaibi.shop.common.entity.enums
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret:  shuaiBi #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

# MinIO对象存储相关配置
minio:
  endpoint: http://121.5.40.72:9000 #MinIO服务所在地址
  bucketName: shop #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥