server:
  port: 9000
spring:
  application:
    name: Shop-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Shop-System
          uri: lb://Shop-System
          predicates:
            - Path=/system/**
        - id: Shop-Product
          uri: lb://Shop-Product
          predicates:
            - Path=/product/**
        - id: Shop-Personal
          uri: lb://Shop-Personal
          predicates:
            - Path=/personal/**
      default-filters:
        - StripPrefix=1
    #service-consumer
    nacos:
      discovery:
        server-addr: 121.5.40.72:8848 #注册中心地址

# 自定义jwt key
jwt:
  secret:  shuaiBi #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)